openapi: 3.0.0

info: 
  title: Vigilion API
  description: API per la web app Vigilion
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Localhost server

paths:
  /authentication:
    post:
      summary: Autenticazione dell'utente
      description: Autentica l'utente e ritorna il token JWT
      responses:
        '200':
          description: Token creato
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: True se l'autenticazione è riuscita, false altrimenti
                  token:
                    type: string
                    description: Token JWT per l'autenticazione
        '401':
          description: Credenziali non valide
      requestBody:
        description: Credenziali per l'autenticazione (email e password)
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: Email dell'utente
                password:
                  type: string
                  description: Password dell'utente
  /authentication/logout:
    post:
      summary: Logout dell'utente
      description: Effettua il logout dell'utente cancellando il cookie di autenticazione
      responses:
        '200':
          description: Logout effettuato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: True se il logout è riuscito
                  message:
                    type: string
                    description: Messaggio di conferma del logout
  /authentication/check:
    get:
      summary: Verifica autenticazione
      description: Verifica se l'utente è autenticato controllando il cookie di autenticazione
      responses:
        '200':
          description: Stato dell'autenticazione
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    description: True se l'utente è autenticato
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                        description: Email dell'utente autenticato
                      id:
                        type: string
                        description: ID dell'utente autenticato
  /users/{id}:
    summary: Rappresentazione di un utente
    description: La risorsa rappresenta un utente univocamente. Ogni utente è identificato da un id.
    get: 
      summary: Ritorna il singolo utente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID dell'utente
      responses:
        "200":
          description: Singolo utente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/NotFound"

  /userreports/{id}:
    get:
      summary: Ritorna tutte le segnalazioni di un utente
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ID dell'utente
      responses:
        "200":
          description: Lista delle segnalazioni associate all'utente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Report"
        "404":
          $ref: "#/components/responses/NotFound"
    post:
      summary: Crea una relazione tra utente e report
      requestBody:
        description: Relazione utente-report da creare
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserReport"
      responses:
        "201":
          description: Relazione creata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserReport"
        "400":
          $ref: "#/components/responses/BadRequest"

  /users:
    summary: Rappresentazione della lista di utenti
    description: In chiamata GET ritorna la lista di tutti gli utenti registrati, in POST crea un nuovo utente
    get:
      summary: Lista degli utenti
      responses:
        "200":
          description: Lista degli utenti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      summary: Crea un nuovo utente
      requestBody:
        description: Utente da creare
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Utente creato
        "400":
          $ref: "#/components/responses/BadRequest"

  /reports:
    summary: Gestione delle segnalazioni
    description: Creazione in POST di una nuova segnalazione e restituzione in GET di tutte le segnalazioni
    post:
      summary: Creazione nuova segnalazione
      requestBody:
        description: Segnalazione da creare
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Report"
      responses:
        "201":
          description: Segnalazione creata
        "400":
          $ref: "#/components/responses/BadRequest"
    get:
      summary: Lista delle segnalazioni
      responses:
        "200":
          description: Lista delle segnalazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Report"

  /reports/latest:
    summary: Ultime segnalazioni
    description: Recupera le ultime 5 segnalazioni ordinate per data di creazione
    get:
      summary: Ultime 5 segnalazioni
      responses:
        "200":
          description: Lista delle ultime 5 segnalazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Report"
        "404":
          $ref: "#/components/responses/NotFound"

  /reports/{id}:
    summary: Rappresentazione di una segnalazione
    description: La risorsa rappresenta una segnalazione univocamente.
    get: 
      summary: Ritorna la singola segnalazione
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID della segnalazione
      responses:
        "200":
          description: Singola segnalazione
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Report"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstname
        - lastname
        - email
        - password
        - circoscrizione
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string
    Report:
      type: object
      required:
        - user
        - typology
        - notes
        - location
        - upvote
        - downvote
        - createdtime
      properties:
        id:
          type: integer
          description: ID autogenerato della segnalazione
        user:
          type: string
          description: ID dell'utente
        typology:
          type: string
          enum: [Furto, Aggressione, Molestia, Soggetto armato, Soggetto alterato, Altro]
          description: Tipologia della segnalazione
        notes:
          type: string
          description: Descrizione della segnalazione
        location:
          type: string
          description: Posizione della segnalazione (latitudine/longitudine)
        upvote:
          type: integer
          description: Numero di upvote ricevuti
        downvote:
          type: integer
          description: Numero di downvote ricevuti
        createdtime:
          type: string
          description: Data e ora di creazione della segnalazione (formato yyyy-mm-dd HH:ii)
    UserReport:
      type: object
      required:
        - user
        - report
      properties:
        user:
          type: string
          description: ID dell'utente
        report:
          type: integer
          description: ID del report
  responses:
    NotFound:
      description: Risorsa non trovata
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Risorsa non trovata
    BadRequest:
      description: Richiesta non valida
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Parametri non validi