openapi: 3.0.0

info: 
  title: Vigilion API
  description: API per la web app Vigilion
  version: 1.0.0

servers:
  - url: http://localhost:8000/api/v1
    description: Production server

paths:
  /users/{id}:
    summary: Rappresentazione di un utente
    description: La risorsa rappresenta un utente univocamente. Ogni utente è identificato da un id.
    get: 
      summary: Ritorna il singolo utente
      responses:
        "200":
          description: Singolo utente
          content:
            application/json:
              schema: 
                type: string
                items:
                  type: string
    post:
      summary: Crea un nuovo utente
      requestBody:
        description: Utente da creare
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Utente creato

components:
  schemas:
    User:
      type: object
      required:
        - id
        - firstname
        - lastname
        - email
        - password
      properties:
        id:
          type: integer
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        password:
          type: string